spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  lifecycle:
    timeout-per-shutdown-phase: 30s   # 优雅停机宽限期时间

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    # 打印sql到控制台
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

shiro:
  noLoginUrls: /favicon.ico,/user/login,/actuator/*
  # cache和session不一样，所以设置cache=false
  cachingEnabled: true
  authenticationCachingEnabled: true
  authenticationCacheName: authenticationCache

# actuator监控配置
management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'    # shutdown 节点默认是不暴露的
  endpoint:
    shutdown:
      enabled: true
    configprops:
      enabled: true

server:
  shutdown: graceful    # 开启优雅停机, 如果不配置是默认IMMEDIATE, 立即停机
